gec:
  normal:
    rankdir: LR
    style: "rounded,filled"
    color: black
    fillcolor: lightgrey
    node:
      color: black
      fillcolor: white
      shape: box
      style: "rounded,filled"
    edge:
      arrowhead: dot
  entity:
    node:
      fillcolor: lightblue
  external:
    node:
      color: "#D08101"
      fontcolor: "#222222"
      fillcolor: "#FEFE82"
    edge:
      color: "#1E1201"
  disabled:
    node:
      fillcolor: lightgrey
      fontcolor: "#aaaaaa"
      color: "#aaaaaa"
    edge:
      color: "#aaaaaa"
